### ISSUE TITLE
Pipes fails to deploy modules when mlHost != localhost

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#14]
@danielholgate , can you please copy/paste your stack trace? Thanks!

**Comment by danielholgate** [comment]
`10:28:46.826 [main] INFO  c.m.pipes.ui.BackendModulesManager - Will copy MarkLogic backend modules to following DHF root: /space/software/DHF/DHF-VPP-TEST
10:28:46.870 [main] INFO  c.m.pipes.ui.BackendModulesManager - MarkLogic backend modules copied to your DHF project.
10:28:46.870 [main] INFO  c.m.pipes.ui.BackendModulesManager - Now loading Pipes modules to your DHF modules database...
10:28:47.303 [main] INFO  c.m.c.e.m.impl.AssetFileLoader - Writing 1 files
10:28:47.303 [main] INFO  c.m.c.e.m.impl.AssetFileLoader - Writing: /custom-modules/pipes/user.sjs
10:28:47.390 [main] ERROR c.m.pipes.ui.BackendModulesManager - Aborting Pipes start-up - Failed to load modules: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8000
10:28:47.462 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.marklogic.pipes.ui.Proxy.main(Proxy.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: com.marklogic.client.MarkLogicIOException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8000
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:759)
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:752)
	at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4138)
	at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3439)
	at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3547)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:54)
	at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:80)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at com.marklogic.client.ext.batch.BatchWriterSupport.executeRunnable(BatchWriterSupport.java:94)
	at com.marklogic.client.ext.batch.RestBatchWriter.write(RestBatchWriter.java:53)
	at com.marklogic.client.ext.file.GenericFileLoader.writeBatchOfDocuments(GenericFileLoader.java:119)
	at com.marklogic.client.ext.file.GenericFileLoader.loadFiles(GenericFileLoader.java:77)
	at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.loadAssets(DefaultModulesLoader.java:366)
	at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.loadModules(DefaultModulesLoader.java:176)
	at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.loadModules(DefaultModulesLoader.java:153)
	at com.marklogic.appdeployer.command.modules.LoadModulesCommand.loadModulesIntoMainServer(LoadModulesCommand.java:69)
	at com.marklogic.appdeployer.command.modules.LoadModulesCommand.execute(LoadModulesCommand.java:42)
	at com.marklogic.appdeployer.impl.AbstractAppDeployer.executeCommand(AbstractAppDeployer.java:101)
	at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:85)
	at com.marklogic.pipes.ui.BackendModulesManager.deployMlBackendModulesToModulesDatabase(BackendModulesManager.java:181)
	at com.marklogic.pipes.ui.BackendModulesManager.copyAndDeployPipesBackend(BackendModulesManager.java:96)
	at com.marklogic.pipes.ui.BackendModulesManager.run(BackendModulesManager.java:78)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
	... 13 common frames omitted
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8000
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:248)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:757)
	... 41 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
	... 62 common frames omitted
`

**Comment by sashamitrovich** [comment]
Fixed and tested.
