### ISSUE TITLE
Pipes doesn't start if credentials not defined in properties

### ISSUE THREAD

**Issue by danielholgate** [marklogic-community/pipes#234]
When mlUsername and mlPassword not defined in application.properties
then a Java exception occurs
```09:54:55.099 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.marklogic.pipes.ui.Application.main(Application.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NullPointerException: null
	at com.marklogic.pipes.ui.BackendModules.BackendModulesAppRunner.run(BackendModulesAppRunner.java:113)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
	... 13 common frames omitted

**Comment by sashamitrovich** [comment]
Fixed.
